# path to root directory containing training example data
root_dir: /home/sean/Desktop/training_examples/

# path to image subdirectory (relative to "root_path")
images_dir: images/

# path to database
db_dir: database/
db_name: training_examples.sl3